src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'text')]
    private $content;

    #[ORM\Column(type: 'datetime_immutable')]
    private $created_at;

    #[ORM\Column(type: 'datetime_immutable')]
    private $update_at;

    #[ORM\Column(type: 'boolean')]
    private $published;

    #[ORM\ManyToMany(targetEntity: Category::class, inversedBy: 'user')]
    private $category;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'posts')]
    private $user;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: Comment::class, orphanRemoval: true)]
    private $comments;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: LikePost::class, orphanRemoval: true)]
    private $likePosts;

    public function __construct()
    {
        $this->category = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->likePosts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdateAt(): string
    {
        return $this->update_at->format('Y-m-d H:i:s');
    }

    public function setUpdateAt(\DateTimeImmutable $update_at): self
    {
        $this->update_at = $update_at;

        return $this;
    }

    public function getPublished(): ?bool
    {
        return $this->published;
    }

    public function setPublished(bool $published): self
    {
        $this->published = $published;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategory(): Collection
    {
        return $this->category;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->category->contains($category)) {
            $this->category[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        $this->category->removeElement($category);

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|LikePost[]
     */
    public function getLikePosts(): Collection
    {
        return $this->likePosts;
    }

    public function addLikePost(LikePost $likePost): self
    {
        if (!$this->likePosts->contains($likePost)) {
            $this->likePosts[] = $likePost;
            $likePost->setPost($this);
        }

        return $this;
    }

    public function removeLikePost(LikePost $likePost): self
    {
        if ($this->likePosts->removeElement($likePost)) {
            // set the owning side to null (unless already changed)
            if ($likePost->getPost() === $this) {
                $likePost->setPost(null);
            }
        }

        return $this;
    }
}

src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Post;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('content')
            ->add('category', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'name',
                'multiple' => true
            ])
            ->add('user', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'firstname'
            ])
            ->add('envoyer', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Form\PostType;
use App\Repository\PostRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/post', name: 'post_')]
class PostController extends AbstractController
{
    #[Route('/view', name: 'view')]
    public function index(PostRepository $posts): Response
    {
        return $this->render('post/index.html.twig', [
            'controller_name' => 'PostController',
            'posts' => $posts->findAll(),
        ]);
    }

    #[Route('/find/{id<\d+>}', name: 'findOne')]
    public function findOne(Post $post): Response
    {
        return $this->render('post/findOne.html.twig', [
            'post' =>  $post
        ]);
    }

    #[Route('/delete/{id<\d+>}', name: 'delete')]
    #[IsGranted('ROLE_EDITOR')]
    public function delete(Post $post, EntityManagerInterface $manager): Response
    {
        $manager->remove($post);
        $manager->flush();

        return $this->redirectToRoute('post_view');
    }

    #[Route('/formulaire/editor/{id?}', name: 'form')]
    #[IsGranted('ROLE_EDITOR')]
    public function create(Post $post = null, Request $request, EntityManagerInterface $manager): Response
    {

        if (!$post) {
            $post = new Post();
            $post->setCreatedAt(new \DateTimeImmutable('now'));
        }
        $form = $this->createForm(PostType::class, $post);

        if($form->handleRequest($request)->isSubmitted() && $form->isValid()) {
            $post
                ->setUpdateAt(new \DateTimeImmutable('now'))
                ->setPublished(true);

            $manager->persist($post);
            $manager->flush();

            return $this->redirectToRoute('home');
        }

        return $this->renderForm('post/form.html.twig', [
            'form' => $form
        ]);
    }
}

templates/post/findOne.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PostController!{% endblock %}

{% block body %}
    <h1>{{ post.title }}</h1>
    <p>{{ post.content }}</p>
    <p>Posté par {{ post.user.firstname }} le {{ post.updateAt }}</p>
    {% for comment in post.comments %}
        <p>Commenté par {{ comment.user.firstname }} - le {{ comment.updateAt }}</p>
        <p>{{ comment.content }}</p>
    {% endfor %}
    {% if is_granted('ROLE_USER') %}
        {{ render(path('comment_form', {'id': post.id})) }}
    {% else %}
        <p>Vous devez etre <a href="{{ path('user_login') }}">connecté</a> pour pouvoir commenter</p>
    {% endif %}

{% endblock %}

templates/post/form.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PostController!{% endblock %}

{% block body %}

    {{ form_start(form) }}
        <div>
            {{ form_label(form.title, 'Titre') }}
            {{ form_widget(form.title, {'attr': {'placeholder': 'entrez votre titre', 'class': 'input-post'}}) }}
        </div>
        <div>
            {{ form_label(form.content, 'Content') }}
            {{ form_widget(form.content, {'attr': {'placeholder': 'entrez votre contenue', 'class': 'input-post'}}) }}
        </div>
        <div>
            {{ form_label(form.category, 'Categorie') }}
            {{ form_widget(form.category, {'attr': {'class': 'input-post'}}) }}
        </div>
        <div>
            {{ form_label(form.user, 'User') }}
            {{ form_widget(form.user, {'attr': {'class': 'input-post'}}) }}
        </div>
    {{ form_end(form) }}

{% endblock %}

templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PostController!{% endblock %}

{% block body %}

    {% for post in posts %}
        <div>
            {{ post.title }} -
            <a href="{{ path('post_findOne', {'id': post.id}) }}"> voir</a> -
            <a href="{{ path('post_delete', {'id': post.id}) }}"> supprimer</a> -
            <a href="{{ path('post_form', {'id': post.id}) }}"> modifier</a>
        </div>
    {% endfor %}

{% endblock %}